#%RAML 1.0 Trait

queryParameters:
      SourceCity:
        required: true
        type: string
        example:
          "Delhi"
      checkInDate:
        required: false
        type: date-only
      checkOutDate:
        required: false
        type: date-only
